name: sacred2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  flutter: 
    sdk: flutter
  path_provider: ^2.0.2
  uuid: ^3.0.4

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  at_client_mobile: ^2.0.0
  at_server_status: ^1.0.0
  at_onboarding_flutter: ^2.1.0

flutter: 
  uses-material-design: true

