// class Autogenerated {
//   int? otherthings;
//   String? appname;
//   List<Passwords>? passwords;
//   List<Ids>? ids;
//   List<Infos>? infos;

//   Autogenerated(
//       {this.otherthings, this.appname, this.passwords, this.ids, this.infos});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     otherthings = json['Otherthings'];
//     appname = json['Appname'];
//     if (json['Passwords'] != null) {
//       passwords = <Passwords>[];
//       json['Passwords'].forEach((v) {
//         passwords!.add(new Passwords.fromJson(v));
//       });
//     }
//     if (json['ids'] != null) {
//       ids = <Ids>[];
//       json['ids'].forEach((v) {
//         ids!.add(new Ids.fromJson(v));
//       });
//     }
//     if (json['infos'] != null) {
//       infos = <Infos>[];
//       json['infos'].forEach((v) {
//         infos!.add(new Infos.fromJson(v));
//       });
//     }
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['Otherthings'] = this.otherthings;
//     data['Appname'] = this.appname;
//     if (this.passwords != null) {
//       data['Passwords'] = this.passwords!.map((v) => v.toJson()).toList();
//     }
//     if (this.ids != null) {
//       data['ids'] = this.ids!.map((v) => v.toJson()).toList();
//     }
//     if (this.infos != null) {
//       data['infos'] = this.infos!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

// class Passwords {
//   String? username;
//   String? pass;

//   Passwords({this.username, this.pass});

//   Passwords.fromJson(Map<String, dynamic> json) {
//     username = json['username'];
//     pass = json['pass'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['username'] = this.username;
//     data['pass'] = this.pass;
//     return data;
//   }
// }

// class Ids {
//   String? idno;
//   String? idname;

//   Ids({this.idno, this.idname});

//   Ids.fromJson(Map<String, dynamic> json) {
//     idno = json['idno'];
//     idname = json['Idname'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['idno'] = this.idno;
//     data['Idname'] = this.idname;
//     return data;
//   }
// }

// class Infos {
//   String? firstName;
//   String? lastName;

//   Infos({this.firstName, this.lastName});

//   Infos.fromJson(Map<String, dynamic> json) {
//     firstName = json['FirstName'];
//     lastName = json['LastName'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['FirstName'] = this.firstName;
//     data['LastName'] = this.lastName;
//     return data;
//   }
// }
